enum StateActionType {
	APPSHELL_LOADING = 'APPSHELL_LOADING',
	APPSHELL_SHOW_SIDEMENU = 'APPSHELL_SHOW_SIDEMENU',

	HUB_SET_USER_HUBS = 'HUB_SET_USER_HUBS',
	HUB_SET_ALL = 'HUB_SET_ALL',

	POST_ADD = 'POST_ADD',
	POST_UPDATE = 'POST_UPDATE',

	POST_SET = 'POST_SET',
	POST_FAV_ACTION = 'POST_FAV_ACTION',
	POST_REVEAL = 'POST_REVEAL',
	POST_USER_FOLLOWS = 'POST_USER_FOLLOWS',
	POST_SWIPED = 'POST_SWIPED',
	POST_MEDIA_MOVE_HEAD = 'POST_MEDIA_MOVE_HEAD',

	POSTS_CLEAR = 'POSTS_CLEAR',
	POST_SET_MUTED = 'POST_SET_MUTED',
	POST_SET_PLAYING = 'POST_SET_PLAYING',

	POPUPS_SNACKBAR = 'POPUPS_SNACKBAR',
	POPUPS_MSG = 'POPUPS_MSG',
	POPUPS_FULLSCREEN = 'POPUPS_FULLSCREEN',
	POPUPS_GLOBAL_SLIDING_POPUP = 'POPUPS_GLOBAL_SLIDING_POPUP',
	POPUPS_GLOBAL_POPUP_BASE = 'POPUPS_GLOBAL_POPUP_BASE',

	APPSHELL_SET_LAST_URL_CHANGE = 'APPSHELL_SET_LAST_URL_CHANGE',

	PM_THREADS_SET = 'PM_THREADS_SET',
	PM_THREADS_UPDATE_ONE = 'PM_THREADS_UPDATE_ONE',
	PM_SET_MSGLIST = 'PM_SET_MSGLIST',
	PM_APPEND_MSG = 'PM_APPEND_MSG',
	PM_THREAD_MARK_READ_LOCAL = 'PM_THREAD_MARK_READ_LOCAL',

	MY_SET = 'MY_SET',
	MY_SET_UNREAD_NOTIF_COUNT = 'MY_SET_UNREAD_NOTIF_COUNT',
	MY_SET_UNREAD_PM_COUNT = 'MY_SET_UNREAD_PM_COUNT',

	PING = 'PING',

	NOTIF_SET = 'NOTIF_SET',
	NOTIF_MARK_READ = 'NOTIF_MARK_READ',
	NOTIF_PUSH_NOTIF_GRANTED = 'NOTIF_PUSH_NOTIF_GRANTED',

	COMMENT_ADD_ACTION = 'COMMENT_ADD_ACTION',
	COMMENTS_SET_BY_POST_ID = 'COMMENTS_SET_BY_POST_ID',
	COMMENTS_IS_WRITING = 'COMMENTS_IS_WRITING',
	COMMENTS_CLEAR = 'COMMENTS_CLEAR',
}

export default StateActionType;
